name: Build Project

on:
    push:
        branches:
          - main
    pull_request:
        branches:
          - main

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build Project

        steps:
          - name: Checkout code
            user: actions/checkout@v4

          - name: Setup .Net Core
            run: actions/setup-dotnet@v4
            with:
              dotnet-version: '8.x'

          - name: Build Project
            run: dotnet restore ./L03.DZA.Project.sln
            run: dotnet build --no-restore ./L03.DZA.Project.sln
