name: Build Project

on:
    push:
        branches:
          - feature
    pull_request:
        branches:
          - feature

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build Project

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup .Net Core
            uses: actions/setup-dotnet@v4
            with:
              dotnet-version: '8.x'

          - name: Build
            run: | 
              dotnet restore ./L03.DZA.Project.sln
              dotnet build --no-restore ./L03.DZA.Project.sln
